Version Bump to 0.22.0
SFDO-Tooling/sfdo-template-helpers pull request #50
Opened 2024-01-18 23:53 UTC by vsbharath

2024-01-18 23:58 UTC, jstvz requested changes
Needs to reflect the next tag, no?

2024-01-18 23:58 UTC, jstvz commented on setup.py
> +    version="0.22.0",  # Required
```suggestion
    version="0.23.0",  # Required
```

2024-01-19 03:44 UTC, vsbharath commented
Thought of deleting the existing tag and re pushing it. So that we don't
have to make any changes for MetaDeploy. If the app fails to pull latest we
can have new tag.


On Thu, Jan 18, 2024, 3:58 PM James Estevez ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Needs to reflect the next tag, no?
> ------------------------------
>
> In setup.py
> <https://github.com/SFDO-Tooling/sfdo-template-helpers/pull/50#discussion_r1458109088>
> :
>
> > @@ -23,7 +23,7 @@
>      name="sfdo-template-helpers",  # Required
>      # https://www.python.org/dev/peps/pep-0440/
>      # https://packaging.python.org/en/latest/single_source_version.html
> -    version="0.20.0",  # Required
> +    version="0.22.0",  # Required
>
> ⬇️ Suggested change
>
> -    version="0.22.0",  # Required
> +    version="0.23.0",  # Required
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SFDO-Tooling/sfdo-template-helpers/pull/50#pullrequestreview-1830762602>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIG5O5WCKSDCFEIAERY7ZGLYPGZK7AVCNFSM6AAAAABCBDHT7GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMZQG43DENRQGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-19 18:32 UTC, jstvz approved these changes

2024-01-19 18:32 UTC, merged

2024-01-19 18:40 UTC, jstvz commented
> Thought of deleting the existing tag and re pushing it. So that we don't have to make any changes for MetaDeploy. If the app fails to pull latest we can have new tag.

Fair enough. I have a bias towards thinking of tags as immutable when they're not.